/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "src/main/IDBC/IBDC_v0.3.3.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(IDBC_AppToDevice, IDBC_AppToDevice, AUTO)


PB_BIND(IDBC_DeviceToApp, IDBC_DeviceToApp, AUTO)


PB_BIND(IDBC_EventNotification, IDBC_EventNotification, AUTO)


PB_BIND(IDBC_ImageInfo, IDBC_ImageInfo, AUTO)


PB_BIND(IDBC_ImageChunk, IDBC_ImageChunk, AUTO)


PB_BIND(IDBC_ImageTransferRequest, IDBC_ImageTransferRequest, AUTO)


PB_BIND(IDBC_EventTransferAck, IDBC_EventTransferAck, AUTO)


PB_BIND(IDBC_DeviceStatus, IDBC_DeviceStatus, AUTO)


PB_BIND(IDBC_PendingEventListRequest, IDBC_PendingEventListRequest, AUTO)


PB_BIND(IDBC_PendingEventList, IDBC_PendingEventList, AUTO)


PB_BIND(IDBC_EventInfoRequest, IDBC_EventInfoRequest, AUTO)


PB_BIND(IDBC_AppTimeRequest, IDBC_AppTimeRequest, AUTO)


PB_BIND(IDBC_AppTimeResponse, IDBC_AppTimeResponse, AUTO)





