/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_IDBC_IBDC_V0_3_2_PB_H_INCLUDED
#define PB_IDBC_IBDC_V0_3_2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Supported image formats. */
typedef enum _IDBC_ImageFormat {
    IDBC_ImageFormat_IMAGE_FORMAT_UNSPECIFIED = 0,
    IDBC_ImageFormat_IMAGE_FORMAT_JPEG = 1,
    IDBC_ImageFormat_IMAGE_FORMAT_PNG = 2
} IDBC_ImageFormat;

/* Struct definitions */
/* Embedded system sends this at event detection. */
typedef struct _IDBC_EventNotification {
    uint32_t event_id; /* Unique ID for each event. */
    uint32_t distance_cm; /* Distance to detected object in centimeters. */
    uint32_t time_offset_ms; /* Time between detection and notification in milliseconds. */
    uint32_t image_count; /* Number of images associated with this event. */
    IDBC_ImageFormat image_format; /* Image format used for this event. */
} IDBC_EventNotification;

/* Metadata describing an individual image.
 Phone can use this information to validate and track image transfer. */
typedef struct _IDBC_ImageInfo {
    uint32_t event_id; /* Event this image belongs to. */
    uint32_t image_index; /* Zero-based image number within the event. */
    uint32_t image_size_bytes; /* Total image size in bytes. */
    uint32_t total_chunks; /* Total number of BLE chunks for this image. */
    IDBC_ImageFormat image_format; /* Format of this image. */
} IDBC_ImageInfo;

typedef PB_BYTES_ARRAY_T(512) IDBC_ImageChunk_payload_t;
/* Header and payload for each image chunk sent over BLE. */
typedef struct _IDBC_ImageChunk {
    uint32_t event_id; /* Event this image belongs to. */
    uint32_t image_index; /* Zero-based image number within the event. */
    uint32_t chunk_sequence; /* Zero-based chunk sequence number. */
    bool is_last_chunk; /* True if this is the final chunk. */
    IDBC_ImageChunk_payload_t payload; /* Raw image bytes contained in this chunk. */
    uint32_t total_chunks; /* Total number of chunks for this image. */
} IDBC_ImageChunk;

/* Phone requests an image transfer.
 Can be used for initial transfer, delayed transfer, or resuming after a disconnect. */
typedef struct _IDBC_ImageTransferRequest {
    uint32_t event_id; /* Event whose images are requested. */
    uint32_t start_from_image; /* Zero-based image index to start from. */
    uint32_t start_from_chunk; /* Zero-based chunk sequence number to start from. */
} IDBC_ImageTransferRequest;

/* Phone acknowledges successful receipt of an entire event and all associated images.
 After this ACK, the embedded system may mark the event complete or delete it to save space. */
typedef struct _IDBC_EventTransferAck {
    uint32_t event_id; /* Event successfully received and validated by the phone. */
} IDBC_EventTransferAck;

/* Phone writes settings to the embedded system. */
typedef struct _IDBC_Settings {
    uint32_t images_per_event; /* Number of images captured per event. */
} IDBC_Settings;

/* Embedded system exposes current device status. */
typedef struct _IDBC_DeviceStatus {
    uint32_t protocol_version; /* Protocol version used by the device. */
    uint32_t battery_percent; /* Battery percentage, 0-100. */
    uint32_t pending_events; /* Number of events not yet acknowledged by the phone. */
    uint32_t storage_available_percent; /* Available storage percentage, 0-100. */
    uint32_t images_per_event_setting; /* Current image per event setting stored on embedded device. */
} IDBC_DeviceStatus;

/* Phone requests a list of pending events.
 Empty message because the list request has no parameters. */
typedef struct _IDBC_PendingEventListRequest {
    char dummy_field;
} IDBC_PendingEventListRequest;

/* Embedded system responds with IDs of events that have not been acknowledged by the phone. */
typedef struct _IDBC_PendingEventList {
    pb_size_t event_ids_count;
    uint32_t event_ids[16]; /* Unique event IDs. */
} IDBC_PendingEventList;

/* Messages the embedded device sends to the phone. */
typedef struct _IDBC_DeviceToApp {
    pb_size_t which_payload;
    union {
        IDBC_EventNotification event_notification;
        IDBC_ImageInfo image_info;
        IDBC_ImageChunk image_chunk;
        IDBC_DeviceStatus device_status;
        IDBC_PendingEventList pending_event_list;
    } payload;
} IDBC_DeviceToApp;

/* Phone requests information for a specific event.
 The embedded system should respond by sending EventNotification for the requested event. */
typedef struct _IDBC_EventInfoRequest {
    uint32_t event_id; /* Event whose notification information is requested. */
} IDBC_EventInfoRequest;

/* Messages the phone sends to the embedded device. */
typedef struct _IDBC_AppToDevice {
    pb_size_t which_payload;
    union {
        IDBC_ImageTransferRequest image_transfer_request;
        IDBC_EventTransferAck event_transfer_ack;
        IDBC_Settings settings;
        IDBC_PendingEventListRequest pending_event_list_request;
        IDBC_EventInfoRequest event_info_request;
    } payload;
} IDBC_AppToDevice;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _IDBC_ImageFormat_MIN IDBC_ImageFormat_IMAGE_FORMAT_UNSPECIFIED
#define _IDBC_ImageFormat_MAX IDBC_ImageFormat_IMAGE_FORMAT_PNG
#define _IDBC_ImageFormat_ARRAYSIZE ((IDBC_ImageFormat)(IDBC_ImageFormat_IMAGE_FORMAT_PNG+1))



#define IDBC_EventNotification_image_format_ENUMTYPE IDBC_ImageFormat

#define IDBC_ImageInfo_image_format_ENUMTYPE IDBC_ImageFormat










/* Initializer values for message structs */
#define IDBC_AppToDevice_init_default            {0, {IDBC_ImageTransferRequest_init_default}}
#define IDBC_DeviceToApp_init_default            {0, {IDBC_EventNotification_init_default}}
#define IDBC_EventNotification_init_default      {0, 0, 0, 0, _IDBC_ImageFormat_MIN}
#define IDBC_ImageInfo_init_default              {0, 0, 0, 0, _IDBC_ImageFormat_MIN}
#define IDBC_ImageChunk_init_default             {0, 0, 0, 0, {0, {0}}, 0}
#define IDBC_ImageTransferRequest_init_default   {0, 0, 0}
#define IDBC_EventTransferAck_init_default       {0}
#define IDBC_Settings_init_default               {0}
#define IDBC_DeviceStatus_init_default           {0, 0, 0, 0, 0}
#define IDBC_PendingEventListRequest_init_default {0}
#define IDBC_PendingEventList_init_default       {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define IDBC_EventInfoRequest_init_default       {0}
#define IDBC_AppToDevice_init_zero               {0, {IDBC_ImageTransferRequest_init_zero}}
#define IDBC_DeviceToApp_init_zero               {0, {IDBC_EventNotification_init_zero}}
#define IDBC_EventNotification_init_zero         {0, 0, 0, 0, _IDBC_ImageFormat_MIN}
#define IDBC_ImageInfo_init_zero                 {0, 0, 0, 0, _IDBC_ImageFormat_MIN}
#define IDBC_ImageChunk_init_zero                {0, 0, 0, 0, {0, {0}}, 0}
#define IDBC_ImageTransferRequest_init_zero      {0, 0, 0}
#define IDBC_EventTransferAck_init_zero          {0}
#define IDBC_Settings_init_zero                  {0}
#define IDBC_DeviceStatus_init_zero              {0, 0, 0, 0, 0}
#define IDBC_PendingEventListRequest_init_zero   {0}
#define IDBC_PendingEventList_init_zero          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define IDBC_EventInfoRequest_init_zero          {0}

/* Field tags (for use in manual encoding/decoding) */
#define IDBC_EventNotification_event_id_tag      1
#define IDBC_EventNotification_distance_cm_tag   2
#define IDBC_EventNotification_time_offset_ms_tag 3
#define IDBC_EventNotification_image_count_tag   4
#define IDBC_EventNotification_image_format_tag  5
#define IDBC_ImageInfo_event_id_tag              1
#define IDBC_ImageInfo_image_index_tag           2
#define IDBC_ImageInfo_image_size_bytes_tag      3
#define IDBC_ImageInfo_total_chunks_tag          4
#define IDBC_ImageInfo_image_format_tag          5
#define IDBC_ImageChunk_event_id_tag             1
#define IDBC_ImageChunk_image_index_tag          2
#define IDBC_ImageChunk_chunk_sequence_tag       3
#define IDBC_ImageChunk_is_last_chunk_tag        4
#define IDBC_ImageChunk_payload_tag              5
#define IDBC_ImageChunk_total_chunks_tag         6
#define IDBC_ImageTransferRequest_event_id_tag   1
#define IDBC_ImageTransferRequest_start_from_image_tag 2
#define IDBC_ImageTransferRequest_start_from_chunk_tag 3
#define IDBC_EventTransferAck_event_id_tag       1
#define IDBC_Settings_images_per_event_tag       1
#define IDBC_DeviceStatus_protocol_version_tag   1
#define IDBC_DeviceStatus_battery_percent_tag    2
#define IDBC_DeviceStatus_pending_events_tag     3
#define IDBC_DeviceStatus_storage_available_percent_tag 4
#define IDBC_DeviceStatus_images_per_event_setting_tag 5
#define IDBC_PendingEventList_event_ids_tag      1
#define IDBC_DeviceToApp_event_notification_tag  1
#define IDBC_DeviceToApp_image_info_tag          2
#define IDBC_DeviceToApp_image_chunk_tag         3
#define IDBC_DeviceToApp_device_status_tag       4
#define IDBC_DeviceToApp_pending_event_list_tag  5
#define IDBC_EventInfoRequest_event_id_tag       1
#define IDBC_AppToDevice_image_transfer_request_tag 1
#define IDBC_AppToDevice_event_transfer_ack_tag  2
#define IDBC_AppToDevice_settings_tag            3
#define IDBC_AppToDevice_pending_event_list_request_tag 4
#define IDBC_AppToDevice_event_info_request_tag  5

/* Struct field encoding specification for nanopb */
#define IDBC_AppToDevice_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,image_transfer_request,payload.image_transfer_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,event_transfer_ack,payload.event_transfer_ack),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,settings,payload.settings),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pending_event_list_request,payload.pending_event_list_request),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,event_info_request,payload.event_info_request),   5)
#define IDBC_AppToDevice_CALLBACK NULL
#define IDBC_AppToDevice_DEFAULT NULL
#define IDBC_AppToDevice_payload_image_transfer_request_MSGTYPE IDBC_ImageTransferRequest
#define IDBC_AppToDevice_payload_event_transfer_ack_MSGTYPE IDBC_EventTransferAck
#define IDBC_AppToDevice_payload_settings_MSGTYPE IDBC_Settings
#define IDBC_AppToDevice_payload_pending_event_list_request_MSGTYPE IDBC_PendingEventListRequest
#define IDBC_AppToDevice_payload_event_info_request_MSGTYPE IDBC_EventInfoRequest

#define IDBC_DeviceToApp_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,event_notification,payload.event_notification),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,image_info,payload.image_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,image_chunk,payload.image_chunk),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_status,payload.device_status),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pending_event_list,payload.pending_event_list),   5)
#define IDBC_DeviceToApp_CALLBACK NULL
#define IDBC_DeviceToApp_DEFAULT NULL
#define IDBC_DeviceToApp_payload_event_notification_MSGTYPE IDBC_EventNotification
#define IDBC_DeviceToApp_payload_image_info_MSGTYPE IDBC_ImageInfo
#define IDBC_DeviceToApp_payload_image_chunk_MSGTYPE IDBC_ImageChunk
#define IDBC_DeviceToApp_payload_device_status_MSGTYPE IDBC_DeviceStatus
#define IDBC_DeviceToApp_payload_pending_event_list_MSGTYPE IDBC_PendingEventList

#define IDBC_EventNotification_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   distance_cm,       2) \
X(a, STATIC,   SINGULAR, UINT32,   time_offset_ms,    3) \
X(a, STATIC,   SINGULAR, UINT32,   image_count,       4) \
X(a, STATIC,   SINGULAR, UENUM,    image_format,      5)
#define IDBC_EventNotification_CALLBACK NULL
#define IDBC_EventNotification_DEFAULT NULL

#define IDBC_ImageInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   image_index,       2) \
X(a, STATIC,   SINGULAR, UINT32,   image_size_bytes,   3) \
X(a, STATIC,   SINGULAR, UINT32,   total_chunks,      4) \
X(a, STATIC,   SINGULAR, UENUM,    image_format,      5)
#define IDBC_ImageInfo_CALLBACK NULL
#define IDBC_ImageInfo_DEFAULT NULL

#define IDBC_ImageChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   image_index,       2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_sequence,    3) \
X(a, STATIC,   SINGULAR, BOOL,     is_last_chunk,     4) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           5) \
X(a, STATIC,   SINGULAR, UINT32,   total_chunks,      6)
#define IDBC_ImageChunk_CALLBACK NULL
#define IDBC_ImageChunk_DEFAULT NULL

#define IDBC_ImageTransferRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   start_from_image,   2) \
X(a, STATIC,   SINGULAR, UINT32,   start_from_chunk,   3)
#define IDBC_ImageTransferRequest_CALLBACK NULL
#define IDBC_ImageTransferRequest_DEFAULT NULL

#define IDBC_EventTransferAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1)
#define IDBC_EventTransferAck_CALLBACK NULL
#define IDBC_EventTransferAck_DEFAULT NULL

#define IDBC_Settings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   images_per_event,   1)
#define IDBC_Settings_CALLBACK NULL
#define IDBC_Settings_DEFAULT NULL

#define IDBC_DeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   battery_percent,   2) \
X(a, STATIC,   SINGULAR, UINT32,   pending_events,    3) \
X(a, STATIC,   SINGULAR, UINT32,   storage_available_percent,   4) \
X(a, STATIC,   SINGULAR, UINT32,   images_per_event_setting,   5)
#define IDBC_DeviceStatus_CALLBACK NULL
#define IDBC_DeviceStatus_DEFAULT NULL

#define IDBC_PendingEventListRequest_FIELDLIST(X, a) \

#define IDBC_PendingEventListRequest_CALLBACK NULL
#define IDBC_PendingEventListRequest_DEFAULT NULL

#define IDBC_PendingEventList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   event_ids,         1)
#define IDBC_PendingEventList_CALLBACK NULL
#define IDBC_PendingEventList_DEFAULT NULL

#define IDBC_EventInfoRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1)
#define IDBC_EventInfoRequest_CALLBACK NULL
#define IDBC_EventInfoRequest_DEFAULT NULL

extern const pb_msgdesc_t IDBC_AppToDevice_msg;
extern const pb_msgdesc_t IDBC_DeviceToApp_msg;
extern const pb_msgdesc_t IDBC_EventNotification_msg;
extern const pb_msgdesc_t IDBC_ImageInfo_msg;
extern const pb_msgdesc_t IDBC_ImageChunk_msg;
extern const pb_msgdesc_t IDBC_ImageTransferRequest_msg;
extern const pb_msgdesc_t IDBC_EventTransferAck_msg;
extern const pb_msgdesc_t IDBC_Settings_msg;
extern const pb_msgdesc_t IDBC_DeviceStatus_msg;
extern const pb_msgdesc_t IDBC_PendingEventListRequest_msg;
extern const pb_msgdesc_t IDBC_PendingEventList_msg;
extern const pb_msgdesc_t IDBC_EventInfoRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define IDBC_AppToDevice_fields &IDBC_AppToDevice_msg
#define IDBC_DeviceToApp_fields &IDBC_DeviceToApp_msg
#define IDBC_EventNotification_fields &IDBC_EventNotification_msg
#define IDBC_ImageInfo_fields &IDBC_ImageInfo_msg
#define IDBC_ImageChunk_fields &IDBC_ImageChunk_msg
#define IDBC_ImageTransferRequest_fields &IDBC_ImageTransferRequest_msg
#define IDBC_EventTransferAck_fields &IDBC_EventTransferAck_msg
#define IDBC_Settings_fields &IDBC_Settings_msg
#define IDBC_DeviceStatus_fields &IDBC_DeviceStatus_msg
#define IDBC_PendingEventListRequest_fields &IDBC_PendingEventListRequest_msg
#define IDBC_PendingEventList_fields &IDBC_PendingEventList_msg
#define IDBC_EventInfoRequest_fields &IDBC_EventInfoRequest_msg

/* Maximum encoded size of messages (where known) */
#define IDBC_AppToDevice_size                    20
#define IDBC_DeviceStatus_size                   30
#define IDBC_DeviceToApp_size                    544
#define IDBC_EventInfoRequest_size               6
#define IDBC_EventNotification_size              26
#define IDBC_EventTransferAck_size               6
#define IDBC_IBDC_V0_3_2_PB_H_MAX_SIZE           IDBC_DeviceToApp_size
#define IDBC_ImageChunk_size                     541
#define IDBC_ImageInfo_size                      26
#define IDBC_ImageTransferRequest_size           18
#define IDBC_PendingEventListRequest_size        0
#define IDBC_PendingEventList_size               96
#define IDBC_Settings_size                       6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
